# retention_logic.py

from typing import Dict, Any

def generate_retention_strategy(customer_data: Dict, churn_probability: float, xai_factors: Dict) -> str:
    """
    Generates a personalized retention strategy using a priority-based system.
    This logic will be run by the FastAPI server after prediction.
    """
    
    # Priority 1: Critical Service Failure (Highest Churn Risk)
    if 'Network Quality' in xai_factors:
        return "🚨 **CRITICAL NETWORK ESCALATION:** High Call Interruption Rate detected. Propose compensation and full network inspection."
        
    # Priority 2: High Risk/High Value (Financial)
    if customer_data.get('contract_Month-to-month') == 1 and churn_probability > 0.8:
        return "🎯 **STRATEGY:** DISCOUNTED 12-MONTH CONTRACT OFFER"
    
    # Priority 3: General Outreach
    if churn_probability > 0.5:
        return "This customer is at high risk of churning. We recommend proactive outreach with a general retention offer."
        
    # Low Risk
    return "Customer is low-risk. Recommend monitoring usage trends."

def generate_llm_script_proxy(churn_probability: float, xai_factors: Dict) -> str:
    """
    Simulates a multi-paragraph, personalized email script that would be generated by an LLM (GPT).
    """
    if churn_probability < 0.5:
        return "No intervention script required for this low-risk customer."

    # Identify the primary problem for the LLM to address
    primary_issue = list(xai_factors.values())[0] if xai_factors else "general dissatisfaction"
    
    script = f"""
**Subject:** Proactive Check-in: Ensuring Your Service is 100% Reliable

Dear Valued Customer,

We noticed a potential area of concern with your account, particularly related to **{primary_issue}**. We take your satisfaction seriously, and because your risk of leaving is high ({churn_probability:.2%}), we want to act immediately.

To show our commitment, we are offering you a **complimentary three-month upgrade to our Premium Support Tier** and a **$25 service credit** to offset any inconvenience. We also want to schedule a network technician to review your service quality, free of charge.

Please reply to this email or call us directly at 555-CHURN to claim your offer and discuss your account. We are here to ensure you stay satisfied.

Sincerely,
The ChurnGuard Retention Team
"""
    return script.strip()